---
apiVersion: v1
kind: Namespace
metadata:
  name: dev


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp
  namespace: dev
  labels:
    app: bankapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bankapp
  template:
    metadata:
      labels:
        app: bankapp
    spec:
      containers:
        - name: bankapp
          image: shaikmustafa/dm
          ports:
            - containerPort: 8080
          

---
apiVersion: v1
kind: Service
metadata:
  name: bankapp-service
  namespace: dev
spec:
  selector:
    app: bankapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer 
